create table if not exists public.quiz_questions (
  id text primary key,
  text text not null,
  color text not null check (color in ('rosso', 'giallo', 'verde', 'blu')),
  position integer not null,
  is_short boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quiz_questions_position_idx
  on public.quiz_questions (position);

alter table public.quiz_questions enable row level security;

create policy "public read quiz questions"
  on public.quiz_questions
  for select
  to anon
  using (true);

insert into public.quiz_questions (id, text, color, position, is_short) values
  ('q1', $$Cerco di cogliere le differenze.$$, 'blu', 1, true),
  ('q2', $$Prediligo la sperimentazione rispetto alla teoria.$$, 'giallo', 2, true),
  ('q3', $$Preferisco relazionarmi con poche persone selezionate.$$, 'verde', 3, true),
  ('q4', $$Mi attengo ai fatti.$$, 'blu', 4, true),
  ('q5', $$Tendo a risolvere i problemi utilizzando un approccio graduale.$$, 'verde', 5, true),
  ('q6', $$Mi applico con energia.$$, 'giallo', 6, true),
  ('q7', $$Vivo i conflitti con difficoltà.$$, 'verde', 7, true),
  ('q8', $$Procedo seguendo la razionalità.$$, 'blu', 8, true),
  ('q9', $$Analizzo i fatti.$$, 'blu', 9, false),
  ('q10', $$L'esperienza è fondamentale.$$, 'rosso', 10, true),
  ('q11', $$Sono una persona riservata.$$, 'verde', 11, true),
  ('q12', $$Mi motivano gli obiettivi sfidanti.$$, 'rosso', 12, true),
  ('q13', $$Rifletto sui fatti.$$, 'blu', 13, true),
  ('q14', $$Vivo con intensità le esperienze.$$, 'giallo', 14, true),
  ('q15', $$Mi interessa aiutare gli altri.$$, 'verde', 15, true),
  ('q16', $$Guardo ai risultati.$$, 'rosso', 16, true),
  ('q17', $$Prima la teoria poi la pratica.$$, 'blu', 17, true),
  ('q18', $$Mi attraggono le cose nuove e diverse.$$, 'giallo', 18, true),
  ('q19', $$Ricerco armonia e pace.$$, 'verde', 19, false),
  ('q20', $$Ho senso di responsabilità.$$, 'blu', 20, false),
  ('q21', $$Prima approfondisco poi sperimento.$$, 'blu', 21, false),
  ('q22', $$Mi piace lavorare in team.$$, 'giallo', 22, true),
  ('q23', $$Ascolto i punti di vista degli altri prima di esprimere il mio.$$, 'verde', 23, false),
  ('q24', $$Mi piace la concretezza.$$, 'rosso', 24, true),
  ('q25', $$Agisco e prendo le decisioni cautamente e con attenzione.$$, 'blu', 25, false),
  ('q26', $$Faccio affidamento sulle mie emozioni ed esperienze.$$, 'giallo', 26, false),
  ('q27', $$Tendo a pensare a diversi scenari prima di agire.$$, 'blu', 27, false),
  ('q28', $$Sono una persona dinamica.$$, 'giallo', 28, false),
  ('q29', $$Affronto le situazioni con la logica.$$, 'blu', 29, false),
  ('q30', $$Mi faccio guidare dall’intuito.$$, 'giallo', 30, false),
  ('q31', $$Mi piace prendere decisioni con calma dopo aver riflettuto su molte alternative.$$, 'verde', 31, false),
  ('q32', $$Mi servono le informazioni essenziali per prendere le decisioni.$$, 'rosso', 32, true),
  ('q33', $$Mi motiva la precisione.$$, 'blu', 33, false),
  ('q34', $$In generale parlo più di quanto ascolti.$$, 'giallo', 34, false),
  ('q35', $$Mi baso sulle mie emozioni.$$, 'giallo', 35, false),
  ('q36', $$Mi piace l'azione.$$, 'giallo', 36, false),
  ('q37', $$Elaboro teorie.$$, 'blu', 37, false),
  ('q38', $$Mi annoiano i dettagli.$$, 'giallo', 38, false),
  ('q39', $$Tendo ad accettare le idee altrui.$$, 'verde', 39, false),
  ('q40', $$Quello che apprendo lo metto alla prova.$$, 'rosso', 40, false),
  ('q41', $$Mi pongo molte domande prima di agire.$$, 'blu', 41, false),
  ('q42', $$Spesso prendo delle decisioni d’istinto.$$, 'giallo', 42, false),
  ('q43', $$Di solito ascolto più di quanto parlo.$$, 'verde', 43, false),
  ('q44', $$Mi baso sui risultati che ottengo.$$, 'rosso', 44, false),
  ('q45', $$Analizzo con accuratezza le situazioni.$$, 'blu', 45, false),
  ('q46', $$Cerco di capire facendo le cose.$$, 'rosso', 46, false),
  ('q47', $$Con gli altri sono disponibile.$$, 'verde', 47, false),
  ('q48', $$Mi ritengo una persona efficiente.$$, 'rosso', 48, false),
  ('q49', $$Valuto equamente.$$, 'verde', 49, false),
  ('q50', $$Mi concentro sul presente.$$, 'rosso', 50, false),
  ('q51', $$Rifletto molto prima di agire.$$, 'verde', 51, false),
  ('q52', $$Mi viene facile seguire un processo.$$, 'blu', 52, false),
  ('q53', $$Faccio attente osservazioni.$$, 'blu', 53, false),
  ('q54', $$Mi piace l’azione.$$, 'giallo', 54, false),
  ('q55', $$Spesso prendo decisioni seguendo onde emotive.$$, 'giallo', 55, false),
  ('q56', $$Prediligo gli scambi di informazioni brevi e diretti.$$, 'rosso', 56, false),
  ('q57', $$Mi piace comprendere le cose.$$, 'blu', 57, false),
  ('q58', $$Con gli altri sono disponibile.$$, 'verde', 58, false),
  ('q59', $$Sono le emozioni a guidarmi.$$, 'giallo', 59, false),
  ('q60', $$Sono una persona pragmatica e concreta.$$, 'rosso', 60, false),
  ('q61', $$Preferisco un approccio razionale.$$, 'blu', 61, false),
  ('q62', $$Non ho paura di correre dei rischi.$$, 'giallo', 62, false),
  ('q63', $$Ascolto le mie emozioni prima di prendere delle decisioni.$$, 'giallo', 63, false),
  ('q64', $$Approccio le cose con logica e razionalità.$$, 'blu', 64, false),
  ('q65', $$Soppeso i pro e i contro.$$, 'blu', 65, false),
  ('q66', $$Mi baso sull’intuizione per risolvere situazioni critiche.$$, 'giallo', 66, false),
  ('q67', $$Approccio alle cose con intuito e sensazioni.$$, 'giallo', 67, false),
  ('q68', $$Mi assumo dei rischi senza paura.$$, 'giallo', 68, false),
  ('q69', $$Analizzo le situazioni.$$, 'blu', 69, false),
  ('q70', $$Imparo le cose facendo.$$, 'rosso', 70, false),
  ('q71', $$Tendo a mediare nei conflitti.$$, 'verde', 71, false),
  ('q72', $$Imparo facendo.$$, 'rosso', 72, false),
  ('q73', $$Mi interessano i dettagli.$$, 'blu', 73, false),
  ('q74', $$Mi piace fare tante cose diverse.$$, 'giallo', 74, false),
  ('q75', $$Rimugino sulle cose passate.$$, 'verde', 75, false),
  ('q76', $$Sono una persona proiettata nel futuro.$$, 'giallo', 76, false),
  ('q77', $$Approfondisco e rifletto sulle situazioni.$$, 'verde', 77, false),
  ('q78', $$Mi sento a mio agio nei cambiamenti.$$, 'giallo', 78, false),
  ('q79', $$Prima di agire ci penso bene.$$, 'verde', 79, false),
  ('q80', $$Analizzo i dati in mio possesso, valutando pro e contro.$$, 'blu', 80, false);
